# 2014 Kamal Nasser hello@kamal.io
# https://github.com/kamaln7/ansible-swapfile
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
---
- name: Write swapfile
  command: |
    {% if swapfile_use_dd %}
    dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ vm_swap }} creates={{ swap_file_path }}
    {% else %}
    fallocate -l {{ vm_swap }}M {{ swap_file_path }} creates={{ swap_file_path }}
    {% endif %}
  register: write_swapfile
  when: swapfile_size != false
    
- name: Set swapfile permissions
  file: path={{ swap_file_path }} mode=600
  when: swapfile_size != false

- name: Create swapfile
  command: mkswap {{ swap_file_path }}
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed

- name: Enable swapfile
  command: swapon {{ swap_file_path }}
  when: swapfile_size != false and create_swapfile.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swap_file_path }} none swap sw 0 0" state=present
  when: swapfile_size != false

- name: Configure vm.swappiness
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
  notify: Reload sysctl
  when: swapfile_swappiness != false

- name: Configure vm.vfs_cache_pressure
  lineinfile: dest=/etc/sysctl.conf line="vm.vfs_cache_pressure = {{ swapfile_vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?=" state=present
  notify: Reload sysctl
  when: swapfile_vfs_cache_pressure != false